package com.doorways.neoforge;

import com.doorways.Doorways;
import com.doorways.block.DoorVariant;
import com.doorways.block.DoorwaysContent;
import com.doorways.block.SlidingPanelsBlockEntity;
import java.util.Map;
import java.util.function.Supplier;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.neoforged.bus.api.EventPriority;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.fml.ModContainer;
import net.neoforged.fml.common.Mod;
import net.neoforged.neoforge.common.NeoForge;
import net.neoforged.neoforge.registries.DeferredRegister;

/**
 * NeoForge entrypoint.
 *
 * <p>The difference from Fabric is only <b>when</b>. Here the registries are already frozen by
 * the time the mod is constructed, so nothing may be instantiated early: the factories
 * {@code common} hands over are passed to {@link DeferredRegister} and only run during the
 * registration phase. The door definitions are the same -- they all come from
 * {@link DoorVariant}.
 *
 * <p>Copper oxidation also differs, but not in code: NeoForge wires it through <b>data maps</b>
 * in {@code data/neoforge/data_maps/block/}, generated by the same script that generates the
 * rest of the assets. On Fabric it is a registry call; here it is two JSON files.
 */
@Mod(Doorways.MOD_ID)
public final class DoorwaysNeoForge {

    private static final DeferredRegister.Blocks BLOCKS =
            DeferredRegister.createBlocks(Doorways.MOD_ID);
    private static final DeferredRegister.Items ITEMS =
            DeferredRegister.createItems(Doorways.MOD_ID);
    private static final DeferredRegister<CreativeModeTab> TABS =
            DeferredRegister.create(Registries.CREATIVE_MODE_TAB, Doorways.MOD_ID);
    private static final DeferredRegister<BlockEntityType<?>> BLOCK_ENTITIES =
            DeferredRegister.create(Registries.BLOCK_ENTITY_TYPE, Doorways.MOD_ID);

    private final Map<DoorVariant, Supplier<Block>> doors;

    public DoorwaysNeoForge(IEventBus modEventBus, ModContainer modContainer) {
        DoorwaysContent.Registrar registrar = new DoorwaysContent.Registrar() {
            @Override
            public Supplier<Block> block(ResourceKey<Block> key, Supplier<Block> factory) {
                return BLOCKS.register(key.identifier().getPath(), factory);
            }

            @Override
            public Supplier<Item> item(ResourceKey<Item> key, Supplier<Item> factory) {
                return ITEMS.register(key.identifier().getPath(), factory);
            }

            @Override
            public Supplier<BlockEntityType<SlidingPanelsBlockEntity>> blockEntity(
                    ResourceKey<BlockEntityType<?>> key,
                    Supplier<BlockEntityType<SlidingPanelsBlockEntity>> factory) {
                return BLOCK_ENTITIES.register(key.identifier().getPath(), factory);
            }
        };

        doors = DoorwaysContent.registerAll(Doorways.MOD_ID, registrar);
        Supplier<Item> hinge = DoorwaysContent.registerComponent(
                Doorways.MOD_ID, registrar, DoorwaysContent.HINGE);
        Supplier<Item> track = DoorwaysContent.registerComponent(
                Doorways.MOD_ID, registrar, DoorwaysContent.TRACK);

        // Own tab: with 168 doors, dumping them into a vanilla tab would make it unusable.
        // displayItems runs well after registration, so it can call the suppliers.
        TABS.register("doorways", () -> CreativeModeTab.builder()
                .title(Component.translatable("itemGroup.doorways"))
                .icon(() -> hinge.get().getDefaultInstance())
                .displayItems((parameters, output) -> {
                    output.accept(hinge.get());
                    output.accept(track.get());
                    doors.values().forEach(door -> output.accept(door.get()));
                })
                .build());

        BLOCK_ENTITIES.register(modEventBus);
        BLOCKS.register(modEventBus);
        ITEMS.register(modEventBus);
        TABS.register(modEventBus);

        // On the game bus, not the mod bus: data maps arrive with the datapacks, long after
        // this constructor. See CopperDataMapCheck for why this exists at all.
        //
        // LOWEST because NeoForge itself listens to this event to derive the inverse maps. At
        // normal priority this listener runs first and queries links that do not exist yet.
        NeoForge.EVENT_BUS.addListener(EventPriority.LOWEST, CopperDataMapCheck::onDataMapsUpdated);

        Doorways.init();
    }
}
